[package]
name = "cto-parallel-test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
argon2 = "0.5.0"
diesel = { version = "2.1.0", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
dotenvy = "0.15.7"
jsonwebtoken = "9.3.0"
r2d2 = "0.8.10"
rand = "0.8.5"
rust_decimal = { version = "1.30", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
