[package]
name = "cto-parallel-test"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "8.3.0"
argon2 = { version = "0.5.0", features = ["std"] }
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]

[lib]
name = "cto_parallel_test"
path = "src/lib.rs"
