[package]
name = "ecommerce_catalog"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = { version = "1.30", features = ["serde", "db-diesel-postgres"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.1.0", features = ["postgres", "r2d2", "chrono"] }
r2d2 = "0.8.10"
dotenv = "0.15.0"
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
rust_decimal_macros = "1.30"
tokio = { version = "1.35", features = ["rt", "macros"] }
actix-web = "4.3"
actix-rt = "2.9"
argon2 = "0.5"
jsonwebtoken = "8.3"
rand = "0.8"
