[package]
name = "cto_parallel_test"
version = "0.1.0"
edition = "2021"
license = "UNLICENSED"

[lib]
name = "cto_parallel_test"
path = "src/lib.rs"

[dependencies]
jsonwebtoken = "9.3.0"
argon2 = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
rand_core = { version = "0.6", features = ["getrandom"] }

[dev-dependencies]
serial_test = "2"
