[package]
name = "cto-parallel-test"
version = "0.1.0"
edition = "2021"
license = "UNLICENSED"
publish = false

[lib]
name = "cto_parallel_test"
path = "src/lib.rs"

[dependencies]
actix-web = "4.3.1"
diesel = { version = "2.1.0", features = ["postgres", "r2d2", "chrono", "numeric"] }
r2d2 = "0.8.10"
dotenv = "0.15.0"
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1.30", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "8.3.0"
argon2 = { version = "0.5.0", features = ["std"] }
rand_core = { version = "0.6", features = ["getrandom"] }
bigdecimal = { version = "0.4", features = ["serde"] }

[dev-dependencies]
once_cell = "1.19"
actix-rt = "2.11.0"

[profile.release]
opt-level = 3
lto = true
