[package]
name = "ecommerce_catalog"
version = "0.1.0"
edition = "2021"

[dependencies]
rust_decimal = { version = "1.30", features = ["serde", "db-diesel2-postgres"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "8.3.0"
argon2 = "0.5.0"
rand = "0.8.5"
diesel = { version = "2.1.0", features = ["postgres", "r2d2", "chrono"] }
r2d2 = "0.8.10"
dotenv = "0.15.0"
chrono = { version = "0.4", features = ["serde"] }
actix-web = "4.3.1"
actix-rt = "2.8"
tokio = { version = "1", features = ["full"] }
env_logger = "0.10"
log = "0.4"

[dev-dependencies]
rust_decimal_macros = "1.30"

[lib]
name = "ecommerce_catalog"
path = "src/lib.rs"
